### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by developer239** [miklosme/gl-react-color-blending#4]
Seeing last commit like 1 mont ago I am actually quite surprised.

From fresh clone `npm install` does not work. `yarn install` does not work. `npm update && npm install` doest not work. `yarn upgrade a && yarn install` does not work. Upgrading `react` or `react-native` or other dependencies does not work. `yarn upgrade-interactive` does not work.

One of the issues I had is described here:
https://github.com/facebook/react-native/issues/7308

Another issue that is happening when I for some reason build the files is red screen: 
![screen shot 2017-08-08 at 9 57 39 am](https://user-images.githubusercontent.com/14946081/29061948-0d608bb8-7c20-11e7-879a-2793fcce0259.png)

Or there is problem with:
![screen shot 2017-08-08 at 9 58 22 am](https://user-images.githubusercontent.com/14946081/29061976-2253776a-7c20-11e7-8e55-4d623ac364f9.png)

**Comment by miklosme** [comment]
Fine, you are right.

**Comment by miklosme** [comment]
Updated the package to use the newest React and gl-react api. It should work now, please confirm.

**Comment by developer239** [comment]
Thanks a lot for that I am overwhelmed with work on another project so I will get back to it in about a week or two. I really appreciate your help though. React-native community is small and every working library makes a huge difference. :)

**Comment by miklosme** [comment]
It's working now. Both RN and `gl-react` changes a lot (maybe RN is not anymore, dunno, I'm not working with it), so it's possible for this project to break. Feel free to open a new issue when that happens.
